dollar_hashtag() {
    if [ "$(whoami)" == "root" ] ; then
        echo "#"
    else
        echo "$"
    fi
}

export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m
\]\w\[\033[00m\]$(git_branch)\[\033[00m\]\n$(dollar_hashtag) '
